### ISSUE TITLE
IP address changing every reboot

### ISSUE THREAD

**Issue by llimz** [anmaped/openfang#14]
Hello,

Just in case it helps. With my mijia "white back" camera, the IP address changes on every reboot. After some investigations it seems that the partition read to find the MAC address is empty with this camera. 

If I run:

```
umount /params
mount -t jffs2 /dev/mtdblock9 /params
```

The params folder is empty.

**Comment by anmaped** [comment]
Yes. We have to read the EFuse bits of the wireless chip in order to get the right MAC address.

**Comment by anmaped** [comment]
Fixed dd03c77a03ed773ede2e11c554b3e0a0402edfab

**Comment by llimz** [comment]
Hello, I just tested it with last version commited since the 12th of march and it is working fine. The IP address is now always the same after a reboot.

Nice job by the way ! The new way of setting up the camera settings including Wifi SSID and password is very user friendly (via the web interface).

I still cannot get pictures/video from the camera with v4l2rtspserver but I assume it is normal until a new version/fix is used? I have only 1 frame on the web interface, it is not refreshed. Is there any way to get if possible an mjpeg stream or something?

**Comment by anmaped** [comment]
@llimz Everything is working now even the mjpeg stream. Ask in the openfang gitter chat if you have some issue.
